### ISSUE TITLE
sorry for newbie question

### ISSUE THREAD

**Issue by adrall12** [Samsung-Loki/Thor#12]
how do i open this type of files?

**Comment by adrall12** [comment]
that is how do open the file after downloading it

**Comment by ethical-haquer** [comment]
> that is how do open the file after downloading it

What file? The Linux.zip one?

**Comment by Bodela3** [comment]
I have a similar issue, I cloned it but which command do I use to run it? what is the actual name of the file. sorry for asking such a noobish question, just started using linux.

**Comment by justaCasualCoder** [comment]
You need to download [Linux.zip](https://github.com/Samsung-Loki/Thor/releases/download/1.0.4/Linux.zip) from the releases section. Extract it (`unzip Linux.zip`) , Enter the folder, and run `./TheAirBlow.Thor.Shell`. You may also need to install The [DotNet 7 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/7.0/runtime?cid=getdotnetcore&runtime=console&arch=x64).

**Comment by Bodela3** [comment]
thank you for your help
