### ISSUE TITLE
USB_DT_ENDPOINT assertion fail!

### ISSUE THREAD

**Issue by hdchieh** [Samsung-Loki/Thor#2]
## Description

<img width="824" alt="Screenshot 2023-06-22 201813" src="https://github.com/Samsung-Loki/Thor/assets/33096672/c2ea8a35-88c8-444e-8346-1ef72060be2a">
<img width="280" alt="Screenshot 2023-06-22 201917" src="https://github.com/Samsung-Loki/Thor/assets/33096672/8df438e0-4fcf-46d7-8258-5099af42c2c9">

## Hardware and software
 - Run WIndows subsystem, Ubuntu-22.04.

**Comment by hdchieh** [comment]
<img width="845" alt="Screenshot 2023-06-22 212347" src="https://github.com/Samsung-Loki/Thor/assets/33096672/2c1a61c3-03cd-48dd-9f0f-8daf85c32c0b">

**Comment by hdchieh** [comment]
<img width="845" alt="Screenshot 2023-06-22 212347" src="https://github.com/Samsung-Loki/Thor/assets/33096672/20a58877-bd68-4ccc-86ee-8b6268906a88">

**Comment by l0rb** [comment]
Having the same problem on a galaxy s8. Anything we con do to help debugging?

**Comment by hdchieh** [comment]
> Having the same problem on a galaxy s8. Anything we con do to help debugging?

Mine is S9+(SM-G965U). I forgot to mention.

**Comment by hdchieh** [comment]
@TheAirBlow

**Comment by TheAirBlow** [comment]
> Having the same problem on a galaxy s8. Anything we con do to help debugging?
@hdchieh @l0rb you guys should do the following:
1) Connect the device and do `connect`, but do not proceed
2) Remember the ID of the device (shows as `XXXX:XXXX`)
3) The first number is the BBB (bus), the second one is DDD (device)
4) Upload respective `/dev/bus/usb/BBB/DDD` file here for me to research

**Comment by hdchieh** [comment]
> > Having the same problem on a galaxy s8. Anything we con do to help debugging?
> 
> @hdchieh @l0rb you guys should do the following:
> 
> 1. Connect the device and do `connect`, but do not proceed
> 2. Remember the ID of the device, shows as `(ID BBB:DDD)`
> 3. Upload respective `/dev/bus/usb/BBB/DDD` file here
---
[Bus 001 Device 002 ID 04e8685d Samsung Electronics Co.zip](https://github.com/Samsung-Loki/Thor/files/11872202/Bus.001.Device.002.ID.04e8685d.Samsung.Electronics.Co.zip)

**Comment by a7md8762** [comment]
> 
[042.zip](https://github.com/Samsung-Loki/Thor/files/11873268/042.zip)

**Comment by TheAirBlow** [comment]
I suspect it's cdc_asm, but the second endpoint should stay fine. I'll research the /dev/bus/usb files you guys sent.

**Comment by TheAirBlow** [comment]
> > > Having the same problem on a galaxy s8. Anything we con do to help debugging?
> > 
> > 
> > @hdchieh @l0rb you guys should do the following:
> > 
> > 1. Connect the device and do `connect`, but do not proceed
> > 2. Remember the ID of the device, shows as `(ID BBB:DDD)`
> > 3. Upload respective `/dev/bus/usb/BBB/DDD` file here
> 
> My Device Is: Samsung Tab A7 (SM-T505N)
> 
> [042.zip](https://github.com/Samsung-Loki/Thor/files/11873278/042.zip)

File is zero bytes in size, you didn't do it correctly.

**Comment by TheAirBlow** [comment]
> This descriptor is for devices which support both full and high speed modes. It returns the configuration for the speed mode currently not active. The structure is same as configuration descriptor except for the field value for bDescriptor type, which is 0x07.

Issue found, working on fixing it.

**Comment by a7md8762** [comment]
> > > > Having the same problem on a galaxy s8. Anything we con do to help debugging?
> > > 
> > > 
> > > @hdchieh @l0rb you guys should do the following:
> > > 
> > > 1. Connect the device and do `connect`, but do not proceed
> > > 2. Remember the ID of the device, shows as `(ID BBB:DDD)`
> > > 3. Upload respective `/dev/bus/usb/BBB/DDD` file here
> > 
> > 
> > My Device Is: Samsung Tab A7 (SM-T505N)
> > [042.zip](https://github.com/Samsung-Loki/Thor/files/11873278/042.zip)
> 
> File is zero bytes in size, you didn't do it correctly.

How To Do It?

**Comment by TheAirBlow** [comment]
> > > Having the same problem on a galaxy s8. Anything we con do to help debugging?
> > 
> > 
> > @hdchieh @l0rb you guys should do the following:
> > 
> > 1. Connect the device and do `connect`, but do not proceed
> > 2. Remember the ID of the device, shows as `(ID BBB:DDD)`
> > 3. Upload respective `/dev/bus/usb/BBB/DDD` file here
> 
> [Bus 001 Device 002 ID 04e8685d Samsung Electronics Co.zip](https://github.com/Samsung-Loki/Thor/files/11872202/Bus.001.Device.002.ID.04e8685d.Samsung.Electronics.Co.zip)

I had successfully fixed the issue, it was because of me not properly parsing class dependant descriptors, which now successfully finds valid interface and endpoints. Release soon.

**Comment by TheAirBlow** [comment]
> > > > > Having the same problem on a galaxy s8. Anything we con do to help debugging?
> > > > 
> > > > 
> > > > @hdchieh @l0rb you guys should do the following:
> > > > 
> > > > 1. Connect the device and do `connect`, but do not proceed
> > > > 2. Remember the ID of the device, shows as `(ID BBB:DDD)`
> > > > 3. Upload respective `/dev/bus/usb/BBB/DDD` file here
> > > 
> > > 
> > > My Device Is: Samsung Tab A7 (SM-T505N)
> > > [042.zip](https://github.com/Samsung-Loki/Thor/files/11873278/042.zip)
> > 
> > 
> > File is zero bytes in size, you didn't do it correctly.
> 
> How To Do It?

Follow the 3 steps I sent. You could just copy the file to desktop for ease of uploading - `cp /dev/bus/usb/BBB/DDD ~/Desktop/device.bin`

**Comment by a7md8762** [comment]
> cp /dev/bus/usb/BBB/DDD ~/Desktop/device.bin

Here It Is:
[device.bin.zip](https://github.com/Samsung-Loki/Thor/files/11880213/device.bin.zip)

**Comment by TheAirBlow** [comment]
@l0rb @hdchieh @a7md8762, try out https://github.com/Samsung-Loki/Thor/releases/tag/1.0.2

**Comment by TheAirBlow** [comment]
But, please do not flash bootloader before you make sure anything non-critical (like vbmeta or system as a big file test) else flashes properly. This tool works for me, but it is still highly unstable in terms of device support - I didn't test many.

**Comment by a7md8762** [comment]
Trying To Do `begin odin` And Says: 

Failed to bulk read: Connection timed out (110)

![Screenshot_20230627_124412](https://github.com/Samsung-Loki/Thor/assets/81858682/cd49c15f-346c-45e0-b6fb-cb4414357a0a)
