### ISSUE TITLE
.NET 8 support? (Fedora Linux 40 only have .NET 6 and 8, not 7)

### ISSUE THREAD

**Issue by th1nhhdk** [Samsung-Loki/Thor#20]
## Description
I can't get Thor to run on my Fedora Linux 40 machine because it doesn't have .NET 7 packages

**Comment by ethical-haquer** [comment]
> ## Description
> 
> I can't get Thor to run on my Fedora Linux 40 machine because it doesn't have .NET 7 packages

I would just use [these self-contained builds](https://xdaforums.com/t/linux-galaxy-flasher-a-gui-for-samsung-flash-tools.4636402/#post-89123207) I made. .NET is bundled with them, so you don't have to install it to use them.
