### ISSUE TITLE
Is it possible for the tool to support aarch64?

### ISSUE THREAD

**Issue by 7-75** [Samsung-Loki/Thor#22]
I'm on asahi linux and I would like to use the tool but when I try to run it ofc I get errors becasue the app is looking for x86 libraries

**Comment by ethical-haquer** [comment]
@7-75 
I have self-contained builds of Thor [on XDA](https://xdaforums.com/t/linux-galaxy-flasher-a-gui-for-samsung-flash-tools.4636402/#post-89808682). Try the linux-arm64 build and let me know if it works or not.

**Comment by 7-75** [comment]
Works like a charm, if I can suggest something, could you add those to the github repo page? I bet a lot more people might need those builds! Thanks Again and happy holidays

**Comment by ethical-haquer** [comment]
@7-75 
Yeah, I'll see if I can add those to the readme. Thanks!

**Comment by 7-75** [comment]
@ethical-haquer it seems like the command "flashTar _path_" isn't working properly
![image](https://github.com/user-attachments/assets/66d5b508-8983-470c-82ff-475f46b73a67)

**Comment by ethical-haquer** [comment]
@7-75 
That is [a known issue](https://github.com/Samsung-Loki/Thor/issues/8).
[Here is the work-around](https://github.com/Samsung-Loki/Thor/issues/8#issuecomment-1637229289). Basically you have to extract the .img.lz4 files from each .tar.md5 file, extract each .img.lz4 file, re-compress the newly extracted .img files back into a .tar.

I would say use [Odin4](https://xdaforums.com/t/official-samsung-odin-v4-1-2-1-dc05e3ea-for-linux.4453423/), but it's an x64 binary. You could try using it with [Box64](https://github.com/ptitSeb/box64), but I haven't personally tried doing that.

**Comment by 7-75** [comment]
Okay i did do it with Odin, i wasn't really sure how to follow the work around maybe I'm just tired
