### ISSUE TITLE
Error When Using `begin odin` Command.

### ISSUE THREAD

**Issue by a7md8762** [Samsung-Loki/Thor#3]
When I Try To Do `begin odin` After Connecting To A Device It Says This: 

Failed to bulk read: Connection timed out (110)

![249108814-cd49c15f-346c-45e0-b6fb-cb4414357a0a](https://github.com/Samsung-Loki/Thor/assets/81858682/ec1db7a4-cf68-4f08-bab7-b0aa694e49aa)

**Comment by hdchieh** [comment]
<img width="812" alt="Screenshot 2023-06-27 142908" src="https://github.com/Samsung-Loki/Thor/assets/33096672/9eb29384-b3ea-43a6-b676-e8da4028d2c3">

Having the same problem.

**Comment by hdchieh** [comment]
``` Shell
shell> debug on
Enabled debug logging
shell> connect
[14:41:27 DBG] Number of configurations: 1
[14:41:27 DBG] Number of interfaces: 2
[14:41:27 DBG] ~~~~ Interface index 0 ~~~~
[14:41:27 DBG] Number of endpoints: 1
[14:41:27 DBG] Interface class: 0x02
[14:41:27 DBG] $$ Endpoint index 0 $$
[14:41:27 DBG] !! Class-dependant descriptor, skipping (len = 6 - 2)
[14:41:27 DBG] $$ Endpoint index 0 $$
[14:41:27 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[14:41:27 DBG] $$ Endpoint index 0 $$
[14:41:27 DBG] !! Class-dependant descriptor, skipping (len = 4 - 2)
[14:41:27 DBG] $$ Endpoint index 0 $$
[14:41:27 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[14:41:27 DBG] $$ Endpoint index 0 $$
[14:41:27 DBG] Endpoint address: 0x82
[14:41:27 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 03)
[14:41:27 DBG] !! Interface is invalid, continuing
[14:41:27 DBG] ~~~~ Interface index 1 ~~~~
[14:41:27 DBG] Number of endpoints: 2
[14:41:27 DBG] Interface class: 0x0A
[14:41:27 DBG] $$ Endpoint index 0 $$
[14:41:27 DBG] Endpoint address: 0x01
[14:41:27 DBG] $$ Endpoint index 1 $$
[14:41:27 DBG] Endpoint address: 0x81
[14:41:27 DBG] > Interface is valid, exiting
[14:41:27 DBG] Interface: 0x01, Read Endpoint: 0x81, Write Endpoint: 0x01
Successfully connected to the device!
Now run "begin" with the protocol you need.
shell> begin odin
[14:41:42 DBG] Full exception: System.InvalidOperationException: Failed to bulk read: Timer expired (62)
   at TheAirBlow.Thor.Library.Platform.Linux.BulkRead(Int32 amount, Int32& read, Int32 timeout) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Platform/Linux.cs:line 243
   at TheAirBlow.Thor.Library.Protocols.Odin.Handshake() in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Protocols/Odin.cs:line 30
   at ThorRewrite.Shell.Commands.Begin.RunCommand(State state, List`1 args) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Shell/Commands/Begin.cs:line 21
~~~~~~~^
Failed to bulk read: Timer expired (62)
shell> begin odin
[14:42:07 DBG] Full exception: System.InvalidOperationException: Failed to bulk write: Connection timed out (110)
   at TheAirBlow.Thor.Library.Platform.Linux.BulkWrite(Byte[] buf, Int32 timeout, Boolean zlp) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Platform/Linux.cs:line 211
   at TheAirBlow.Thor.Library.Protocols.Odin.Handshake() in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Protocols/Odin.cs:line 29
   at ThorRewrite.Shell.Commands.Begin.RunCommand(State state, List`1 args) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Shell/Commands/Begin.cs:line 21
~~~~~~~^
Failed to bulk write: Connection timed out (110)
```

**Comment by hdchieh** [comment]
> 

Sadly, failed.
```
root@ :/mnt/m/# ./odin4 -l
/dev/bus/usb/001/003
root@ :/mnt/m/# ./odin4 -a /mnt/j/PixelExperience_Plus_star2qltechn-12.1-20221101-1827-UNOFFICIAL/recovery.img -d /dev/bus/usb/001/003
/dev/bus/usb/001/003
Setup Connection
Fail Setup Connection
```

**Comment by TheAirBlow** [comment]
> > Can you test if leaked `odin4` I published on XDA works in any way? I want a reference point. Additionally, the error code 62 can be just interpreted as a timeout. Also it fails at the handshake, which is really bad. Make sure you have a good connection, and if you disconnect a device from USB in Odin mode and connect it again without rebooting it nothing will work as it "grabs" on the first connection and ignores any further attempts.
> 
> Sadly, failed.
> 
> ```shell
> root@:/mnt/m/# cat  /etc/udev/rules.d/51-android.rules
> SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="0666", GROUP="plugdev"
> root@ :/mnt/m/# ./odin4 -l
> /dev/bus/usb/001/003
> root@ :/mnt/m/# ./odin4 -a /mnt/j/PixelExperience_Plus_star2qltechn-12.1-20221101-1827-UNOFFICIAL/recovery.img -d /dev/bus/usb/001/003
> /dev/bus/usb/001/003
> Setup Connection
> Fail Setup Connection
> ```

I have zero clue. I'll leave this issue as help wanted

**Comment by a7md8762** [comment]
I Got `begin odin` Once To Work (I Do Not Know What I Did To Make It Work, I Remember Flashing The Device With Odin4 For Once, Then Run `sudo modprobe -r cdc_acm` After It Gave Me The Timeout Error), But Trying To Do It Again Gives The Error! It Even Messed Up With Something That Made Odin4 Doesn't Work Anymore And Gives The Same Timeout Error...

**Comment by TheAirBlow** [comment]
> I Got `begin odin` Once To Work (I Do Not Know What I Did To Make It Work, I Remember Flashing The Device With Odin4 For Once, Then Run `sudo modprobe -r cdc_acm` After It Gave Me The Timeout Error), But Trying To Do It Again Gives The Error! It Even Messed Up With Something That Made Odin4 Doesn't Work Anymore And Gives The Same Timeout Error...

Bro... You can't re-use the same USB connection multiple times, or disconnect and reconnect the same device. For that to work, you need to restart it into Download mode each time - it's a quirk of bootloader's USB implementation.

**Comment by TheAirBlow** [comment]
> I Remember Flashing The Device With Odin4 For Once, Then Run sudo modprobe -r cdc_acm After It Gave Me The Timeout Error

Exactly. You didn't restart the device, and odin4 closes the session after it finishes so you MUST reboot.

**Comment by a7md8762** [comment]
> > I Got `begin odin` Once To Work (I Do Not Know What I Did To Make It Work, I Remember Flashing The Device With Odin4 For Once, Then Run `sudo modprobe -r cdc_acm` After It Gave Me The Timeout Error), But Trying To Do It Again Gives The Error! It Even Messed Up With Something That Made Odin4 Doesn't Work Anymore And Gives The Same Timeout Error...
> 
> Bro... You can't re-use the same USB connection multiple times, or disconnect and reconnect the cable. For that to work, you need to restart it into Download mode each time - it's a quirk of bootloader's USB implementation.

I Know! I Reboot My Device Into Download Mode After Each Flash.

**Comment by a7md8762** [comment]
> > I Remember Flashing The Device With Odin4 For Once, Then Run sudo modprobe -r cdc_acm After It Gave Me The Timeout Error
> 
> Exactly. Official odin4 closes the session after it finishes so you MUST reboot, I could have just implemented an option to skip the handshake but eh... The BL is really quirky so it will never work, and also you can't begin a new session after one was ended.

Could You Implement A Feature That Does All The USB Work For You? So You Don't Get Any Connection Errors.
And Can You Make It Auto Begin A Protocol? As There Is Only 1 Option.

And Yes, There Is Something Wrong With `begin odin` Command, It Doesn't Work At All, While Odin4 Connects Without Any Problem And Flash The File.

**Comment by TheAirBlow** [comment]
> > > I Remember Flashing The Device With Odin4 For Once, Then Run sudo modprobe -r cdc_acm After It Gave Me The Timeout Error
> > 
> > 
> > Exactly. Official odin4 closes the session after it finishes so you MUST reboot, I could have just implemented an option to skip the handshake but eh... The BL is really quirky so it will never work, and also you can't begin a new session after one was ended.
> 
> Could You Implement A Feature That Does All The USB Work For You? So You Don't Get Any Connection Errors. And Can You Make It Auto Begin A Protocol? As There Is Only 1 Option.
> 
> And Yes, There Is Something Wrong With `begin odin` Command, It Doesn't Work At All, While Odin4 Connects Without Any Problem And Flash The File (I Got Odin4 Fixed, There Were Something Wrong With The USB, But Thor Completely Refuses To Begin A Protocol).

There is no magic solution. And a program does things for you - nothing is manual. I don't get what you're saying.

**Comment by TheAirBlow** [comment]
@hdchieh @a7md8762 what version of the kernel do you have? Do `uname -a` please

**Comment by TheAirBlow** [comment]
I found this interesting piece of information:
```cpp
/*
* Older versions of usbfs place a 16kb limit on bulk URBs. We work
* around this by splitting large transfers into 16k blocks, and then
* submit all urbs at once. it would be simpler to submit one urb at
* a time, but there is a big performance gain doing it this way.
*
* Newer versions lift the 16k limit (USBFS_CAP_NO_PACKET_SIZE_LIM),
* using arbritary large transfers can still be a bad idea though, as
* the kernel needs to allocate physical contiguous memory for this,
* which may fail for large buffers.
*
* The kernel solves this problem by splitting the transfer into
* blocks itself when the host-controller is scatter-gather capable
* (USBFS_CAP_BULK_SCATTER_GATHER), which most controllers are.
*
* Last, there is the issue of short-transfers when splitting, for
* short split-transfers to work reliable USBFS_CAP_BULK_CONTINUATION
* is needed, but this is not always available.
*/
if (dpriv->caps & USBFS_CAP_BULK_SCATTER_GATHER) {
    /* Good! Just submit everything in one go */
    bulk_buffer_len = transfer->length ? transfer->length : 1;
    use_bulk_continuation = 0;
} else if (dpriv->caps & USBFS_CAP_BULK_CONTINUATION) {
    /* Split the transfers and use bulk-continuation to
        avoid issues with short-transfers */
    bulk_buffer_len = MAX_BULK_BUFFER_LENGTH;
    use_bulk_continuation = 1;
} else if (dpriv->caps & USBFS_CAP_NO_PACKET_SIZE_LIM) {
    /* Don't split, assume the kernel can alloc the buffer
        (otherwise the submit will fail with -ENOMEM) */
    bulk_buffer_len = transfer->length ? transfer->length : 1;
    use_bulk_continuation = 0;
} else {
    /* Bad, splitting without bulk-continuation, short transfers
        which end before the last urb will not work reliable! */
    /* Note we don't warn here as this is "normal" on kernels <
        2.6.32 and not a problem for most applications */
    bulk_buffer_len = MAX_BULK_BUFFER_LENGTH;
    use_bulk_continuation = 0;
}
```

I will work on implementing those soon enough.

**Comment by hdchieh** [comment]
> @hdchieh @a7md8762 what version of the kernel do you have? Do `uname -a` please

Linux HDWD 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

I doubt if it is my Ryzen CPU. There are several posts mentioning it.

* [(2) Odin problem with CPU Ryzen? | XDA Forums](https://forum.xda-developers.com/t/odin-problem-with-cpu-ryzen.3969323/)
* [(2) << SOLVED>>AMD RYZEN and Odin Problems? | XDA Forums](https://forum.xda-developers.com/t/solved-amd-ryzen-and-odin-problems.3775489/)
* [Trouble flashing with Odin : GalaxyS9](https://www.reddit.com/r/GalaxyS9/comments/hp19wd/trouble_flashing_with_odin/)

**Comment by TheAirBlow** [comment]
> > @hdchieh @a7md8762 what version of the kernel do you have? Do `uname -a` please
> 
> Linux HDWD 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> 
> I doubt if it is my Ryzen CPU. There are several posts mentioning it.
> 
>     * [(2) Odin problem with CPU Ryzen? | XDA Forums](https://forum.xda-developers.com/t/odin-problem-with-cpu-ryzen.3969323/)
> 
>     * [(2) << SOLVED>>AMD RYZEN and Odin Problems? | XDA Forums](https://forum.xda-developers.com/t/solved-amd-ryzen-and-odin-problems.3775489/)
> 
>     * [Trouble flashing with Odin : GalaxyS9](https://www.reddit.com/r/GalaxyS9/comments/hp19wd/trouble_flashing_with_odin/)

I don't really think WSL would cut it for low-level communication using native Linux API, but I'll go ahead and implement the cap handling, maybe WSL just ignores all the modern shit and does it the oldest way imaginable... Also, latest kernel version is far, far away, its' 6.x.x already.

**Comment by TheAirBlow** [comment]
Also, hell naw, CPU should not be a problem..? I own a Ryzen 5 laptop.

**Comment by TheAirBlow** [comment]
@hdchieh, as you're using WSL, the kernel is old enough to not have the 16kb limit (other stuff does not apply to my implementation), I'll mark this issue as invalid - WSL will never work like a real Linux install. But, I'll wait for @a7md8762 to respond first.

**Comment by TheAirBlow** [comment]
@hdchieh, additionally, you could try a LiveISO of a distro of your choice and try Thor here (but install .NET 7 Runtime first), but keep in mind anything you do will wiped after you reboot - LiveISO stores all filesystem changes in RAM.

**Comment by hdchieh** [comment]
> @hdchieh, additionally, you could try a LiveISO of a distro of your choice and try Thor here (but install .NET 7 Runtime first), but keep in mind anything you do will wiped after you reboot - LiveISO stores all filesystem changes in RAM.

OK, thanks.

**Comment by a7md8762** [comment]
> @hdchieh @a7md8762 what version of the kernel do you have? Do `uname -a` please

Sorry For Late Reply!

Here: 

Linux K53e 5.15.102-1-MANJARO #1 SMP PREEMPT Mon Mar 13 11:02:38 UTC 2023 x86_64 GNU/Linux

**Comment by TheAirBlow** [comment]
> > @hdchieh @a7md8762 what version of the kernel do you have? Do `uname -a` please
> 
> Sorry For Late Reply!
> 
> Here:
> 
> Linux K53e 5.15.102-1-MANJARO #1 SMP PREEMPT Mon Mar 13 11:02:38 UTC 2023 x86_64 GNU/Linux

Welp, that's fun! I'll keep this issue open and think about ways around it.

**Comment by a7md8762** [comment]
> > > @hdchieh @a7md8762 what version of the kernel do you have? Do `uname -a` please
> > 
> > 
> > Sorry For Late Reply!
> > Here:
> > Linux K53e 5.15.102-1-MANJARO #1 SMP PREEMPT Mon Mar 13 11:02:38 UTC 2023 x86_64 GNU/Linux
> 
> Welp, that's fun! I'll keep this issue open and think about ways around it.

Good Luck Mate!

**Comment by TheAirBlow** [comment]
This really looks similar to the issues with Heimdall, and https://github.com/amo13/Heimdall/commit/745dbb46004a328f0db04cc75b6d4124562591a2 looks to be the fix. Samsung's official tool also do a USBDEVFS_RESET call, so it totally makes sense now. I'll push out a release soon.

**Comment by TheAirBlow** [comment]
I may have to move it elsewhere if it won't fix this issue. @hdchieh @a7md8762, try out https://github.com/Samsung-Loki/Thor/releases/tag/1.0.3

**Comment by hdchieh** [comment]
> I may have to move it elsewhere if it won't fix this issue. @hdchieh @a7md8762, try out https://github.com/Samsung-Loki/Thor/releases/tag/1.0.3
Thank you.
It seems my case won't provide much valid information since I am on WSL. But, anyway, this is my outcome.

```Shell
root@:/mnt/m/LinuxSubsystemFile/Linux# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 04e8:685d Samsung Electronics Co., Ltd GT-I9100 Phone [Galaxy S II] (Download mode)
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

root@HDWD:/mnt/m/LinuxSubsystemFile/Linux# ./TheAirBlow.Thor.Shell
shell> connect
[18:21:13 DBG] Number of configurations: 1
[18:21:13 DBG] Number of interfaces: 2
[18:21:13 DBG] ~~~~ Interface index 0 ~~~~
[18:21:13 DBG] Number of endpoints: 1
[18:21:13 DBG] Interface class: 0x02
[18:21:13 DBG] $$ Endpoint index 0 $$
[18:21:13 DBG] !! Class-dependant descriptor, skipping (len = 6 - 2)
[18:21:13 DBG] !! Interface is invalid, continuing
[18:21:13 DBG] ~~~~ Interface index 1 ~~~~
[18:21:13 DBG] !! USB_DT_INTERFACE fail (value = 24)
[18:21:13 DBG] Number of endpoints: 1
[18:21:13 DBG] Interface class: 0x04
[18:21:13 DBG] $$ Endpoint index 0 $$
[18:21:13 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[18:21:13 DBG] !! Interface is invalid, continuing
[18:21:13 DBG] Full exception: System.InvalidOperationException: Failed to find valid endpoints!
   at TheAirBlow.Thor.Library.Platform.Linux.Initialize(String id, Byte[] direct) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Platform/Linux.cs:line 142
   at ThorRewrite.Shell.Commands.Connect.RunCommand(State state, List`1 args) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Shell/Commands/Connect.cs:line 26
~~~~~~~^
Failed to find valid endpoints!
```

**Comment by TheAirBlow** [comment]
> > I may have to move it elsewhere if it won't fix this issue. @hdchieh @a7md8762, try out https://github.com/Samsung-Loki/Thor/releases/tag/1.0.3
> > Thank you.
> > It seems my case won't provide much valid information since I am on WSL. But, anyway, this is my outcome.
> 
> ```shell
> root@:/mnt/m/LinuxSubsystemFile/Linux# lsusb
> Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 001 Device 003: ID 04e8:685d Samsung Electronics Co., Ltd GT-I9100 Phone [Galaxy S II] (Download mode)
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> 
> root@:/mnt/m/LinuxSubsystemFile/Linux# ./TheAirBlow.Thor.Shell
> shell> connect
> [18:21:13 DBG] Number of configurations: 1
> [18:21:13 DBG] Number of interfaces: 2
> [18:21:13 DBG] ~~~~ Interface index 0 ~~~~
> [18:21:13 DBG] Number of endpoints: 1
> [18:21:13 DBG] Interface class: 0x02
> [18:21:13 DBG] $$ Endpoint index 0 $$
> [18:21:13 DBG] !! Class-dependant descriptor, skipping (len = 6 - 2)
> [18:21:13 DBG] !! Interface is invalid, continuing
> [18:21:13 DBG] ~~~~ Interface index 1 ~~~~
> [18:21:13 DBG] !! USB_DT_INTERFACE fail (value = 24)
> [18:21:13 DBG] Number of endpoints: 1
> [18:21:13 DBG] Interface class: 0x04
> [18:21:13 DBG] $$ Endpoint index 0 $$
> [18:21:13 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
> [18:21:13 DBG] !! Interface is invalid, continuing
> [18:21:13 DBG] Full exception: System.InvalidOperationException: Failed to find valid endpoints!
>    at TheAirBlow.Thor.Library.Platform.Linux.Initialize(String id, Byte[] direct) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Platform/Linux.cs:line 142
>    at ThorRewrite.Shell.Commands.Connect.RunCommand(State state, List`1 args) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Shell/Commands/Connect.cs:line 26
> ~~~~~~~^
> Failed to find valid endpoints!
> ```

That was another bug I fixed already while I was testing the version with a USB reset. I will remove it until further notice - it breaks connectivity with my device and gives a protocol error. In case of @a7md8762, even official `odin4` doesn't work so I believe it's just a broken USB cable or a mutilated USB port.

**Comment by hdchieh** [comment]
> @hdchieh @a7md8762, https://github.com/Samsung-Loki/Thor/releases/tag/1.0.4. Both of you should try the Windows version of Odin (native installation only), and if it doesn't work, I can't help you. Additionally, only native Linux installations are currently supported, I only want you to test Windows Odin to make sure it is my flash tool that is broken and not something on your side. @a7md8762, check your cable and the USB port of your device for any bad signs. Get `odin4` to work first.

Thanks for your tip. It should be something on my side, and I can't make Windows Odin work either.

**Comment by TheAirBlow** [comment]
Sniping off this issue then.
