### ISSUE TITLE
[Question] Should I use this utility ? 

### ISSUE THREAD

**Issue by MrDisguised** [Samsung-Loki/Thor#5]
I use arch btw and I am looking for a odin alternative that I can use to flash my samsung galaxy SM-M307F. Heimdall is horrible because of many reasons - 1) It is complicated because instead of flashing AP,BL,CSC files u have to flash PIT files 2) It didn't work for me and yes I read the manual on how to use it. Only way to root a device in linux is to install odin in a windows virtual machine and then passthrough ur usb to that virtual machine.

So should I use this tool ? Does it work properly as intended ? Will it brick my device ? I know that the developers are not responsible if I brick my device but what are chances of this tool bricking my device ?

**Comment by TheAirBlow** [comment]
It should work, but there is quite a bit of chance that it will fail as this tool wasn't tested on many devices yet. I recommend you to flash vbmeta and system (non-important partitions) as a test to make sure the bootloader won't get trashed. If it then successfully boots, you can continue.
