### ISSUE TITLE
MDM Mode Blocking Me From Flashing.

### ISSUE THREAD

**Issue by a7md8762** [Samsung-Loki/Thor#6]
When I Try To Do `factoryReset` Command It Says On The Device:

**MDM MODE. CAN'T ERASE (userdata)**

Logs:
```
shell> factoryReset
Are you absolutely sure you want to do this? [y/n] (n): y
~~~~~~~^
EraseUserData received 0xFF (code 0xFFFFFFFB)
```

Same Thing When Trying To Flash Via `flashTar` Command, But Instead It Says: 

**MDM MODE. CAN'T DOWNLOAD (userdata)** 

Is There A Way To Bypass MDM Mode? EFT Pro Can Bypass It And I Don't Know How, Just Look At This [Clip](https://www.youtube.com/clip/UgkxJPk7Sk0HCA0f2AmYE8u-CuGfum9DBN3T) Carefully.

**Comment by TheAirBlow** [comment]
> When I Try To Do `factoryReset` Command It Says On The Device:
> 
> **MDM MODE. CAN'T ERASE (userdata)**
> 
> Logs:
> 
> ```
> shell> factoryReset
> Are you absolutely sure you want to do this? [y/n] (n): y
> ~~~~~~~^
> EraseUserData received 0xFF (code 0xFFFFFFFB)
> ```
> 
> Same Thing When Trying To Flash Via `flashTar` Command, But Instead It Says:
> 
> **MDM MODE. CAN'T DOWNLOAD (userdata)**
> 
> Is There A Way To Bypass MDM Mode? EFT Pro Can Bypass It And I Don't Know How, Just Look At This [Clip](https://www.youtube.com/clip/UgkxJPk7Sk0HCA0f2AmYE8u-CuGfum9DBN3T) Carefully.

Would be quite interesting to reverse-engineer this tool...

**Comment by a7md8762** [comment]
> > When I Try To Do `factoryReset` Command It Says On The Device:
> > **MDM MODE. CAN'T ERASE (userdata)**
> > Logs:
> > ```
> > shell> factoryReset
> > Are you absolutely sure you want to do this? [y/n] (n): y
> > ~~~~~~~^
> > EraseUserData received 0xFF (code 0xFFFFFFFB)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Same Thing When Trying To Flash Via `flashTar` Command, But Instead It Says:
> > **MDM MODE. CAN'T DOWNLOAD (userdata)**
> > Is There A Way To Bypass MDM Mode? EFT Pro Can Bypass It And I Don't Know How, Just Look At This [Clip](https://www.youtube.com/clip/UgkxJPk7Sk0HCA0f2AmYE8u-CuGfum9DBN3T) Carefully.
> 
> Would be quite interesting to reverse-engineer this tool...

Yeah! And I would love to finally flash my device... That I have been trying on it for almost a year.
Let me know if you got any information!
Thanks for your help!

**Comment by a7md8762** [comment]
> > When I Try To Do `factoryReset` Command It Says On The Device:
> > **MDM MODE. CAN'T ERASE (userdata)**
> > Logs:
> > ```
> > shell> factoryReset
> > Are you absolutely sure you want to do this? [y/n] (n): y
> > ~~~~~~~^
> > EraseUserData received 0xFF (code 0xFFFFFFFB)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Same Thing When Trying To Flash Via `flashTar` Command, But Instead It Says:
> > **MDM MODE. CAN'T DOWNLOAD (userdata)**
> > Is There A Way To Bypass MDM Mode? EFT Pro Can Bypass It And I Don't Know How, Just Look At This [Clip](https://www.youtube.com/clip/UgkxJPk7Sk0HCA0f2AmYE8u-CuGfum9DBN3T) Carefully.
> 
> Would be quite interesting to reverse-engineer this tool...

Can you implement a feature that ignores any errors Thor receives and just continue without stopping? I think that's how EFT Pro bypasses MDM mode. 
Hopefully, you implement it, It might be useful!

**Comment by TheAirBlow** [comment]
> > > When I Try To Do `factoryReset` Command It Says On The Device:
> > > **MDM MODE. CAN'T ERASE (userdata)**
> > > Logs:
> > > ```
> > > shell> factoryReset
> > > Are you absolutely sure you want to do this? [y/n] (n): y
> > > ~~~~~~~^
> > > EraseUserData received 0xFF (code 0xFFFFFFFB)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Same Thing When Trying To Flash Via `flashTar` Command, But Instead It Says:
> > > **MDM MODE. CAN'T DOWNLOAD (userdata)**
> > > Is There A Way To Bypass MDM Mode? EFT Pro Can Bypass It And I Don't Know How, Just Look At This [Clip](https://www.youtube.com/clip/UgkxJPk7Sk0HCA0f2AmYE8u-CuGfum9DBN3T) Carefully.
> > 
> > 
> > Would be quite interesting to reverse-engineer this tool...
> 
> Can you implement a feature that ignores any errors Thor receives (unless it's a timeout error) and just continue without stopping? I think that's how EFT Pro bypasses MDM mode. Hopefully, you implement it, It might be useful!

Factory reset is a SINGLE packet, and the device sent an error code for it. Nothing I can do about it.

However, I do not have the time to work on Thor as I switched my interest to a different project of mine, so do not expect me to continue for a while.
