### ISSUE TITLE
Missing dll

### ISSUE THREAD

**Issue by lmateovf** [Samsung-Loki/Thor#7]
## Description
missing dll

## Reproduction
1) Enter command `./ThorRewrite.Shell
3) I get the error:
The application to execute does not exist: '/home/xxx/Descargas/linux/ThorRewrite.Shell.dll'.

## Expected behaviour
I expected to work since I installed .NET 7.0 as described in README

## Hardware and software
Linux --> Pop_OS!

## Additional context
![Captura desde 2023-07-15 11-52-03](https://github.com/Samsung-Loki/Thor/assets/62722086/b68d8185-0450-4c75-8661-0c43d821de2c)

**Comment by lmateovf** [comment]
Also, sorry for commenting on one Closed issue, I have opened now this one because I think it's better for you to help me... thank you in advance for your pacience

**Comment by TheAirBlow** [comment]
It was me accidentally mixing up the `bin` folder of mine locally, I forgot to delete the old `ThorRewrite` files. Use `TheAirBlow.Thor.Shell` instead
